- .cirrus.yml
- testdata/ci-wget-tests.bash
- testdata/try-wget-connect.bash
> Add wget tests

- .cirrus.yml
- testdata/ci-chromium-tests.bash
- testdata/try-chromium-connect.bash
Fixes https://github.com/namecoin/pkcs11mod/issues/21
> Cirrus: Add Chromium tests

- COPYING
- COPYING.LESSER
Fixes https://github.com/namecoin/pkcs11mod/issues/8
> Add license text

- .cirrus.yml
- README.md
- p11mod/README.md
- p11mod/backend.go
- p11mod/p11mod.go
- p11proxy/README.md
- p11proxy/p11proxy.go
- testdata/ci-firefox-tests.bash
- testdata/ci-gnutls-cli-tests.bash
- testdata/ci-pkcs11-dump-tests.bash
- testdata/ci-tstclnt-tests.bash
- testdata/ci-wget-tests.bash
- types.go
Fixes https://github.com/namecoin/pkcs11mod/issues/9
> Add p11mod

- p11proxy/README.md
- pkcs11proxy/README.md
This was previously only documented via the Cirrus config.
> README: Document proxy env vars

- testdata/ci-chromium-tests.bash
Fixes https://github.com/namecoin/pkcs11mod/issues/44
> Add Chromium p11proxy test

- p11mod/p11mod.go
- testdata/ci-opendnssec-tests.bash
- testdata/dump-proxy-log-fail.bash
Refs #46
This PR was part of https://github.com/namecoin/pkcs11mod/pull/48 but was split off to keep PR size manageable.
> p11mod: Implement CreateObject

- p11mod/p11mod.go
Refs https://github.com/namecoin/pkcs11mod/issues/46
This PR was originally part of https://github.com/namecoin/pkcs11mod/pull/48 but was split out to keep the PR size manageable.
> p11mod: Implement DestroyObject

- p11mod/p11mod.go
- testdata/ci-opendnssec-tests.bash
> p11mod: Implement GenerateKeyPair

- backend.go
- p11mod/p11mod.go
- pkcs11mod.go
- pkcs11proxy/pkcs11proxy.go
- testdata/ci-tstclnt-tests.bash
Fixes https://github.com/namecoin/pkcs11mod/issues/10
> Fix panic with nil backends

- .cirrus.yml
- pkcs11_exported.c
- testdata/ci-exports-tests.ps1
Fixes https://github.com/namecoin/pkcs11mod/issues/55
> Export C_GetFunctionList on Windows

- .cirrus.yml
- p11proxy/README.md
- pkcs11proxy/README.md
- testdata/ci-exports-tests.ps1
Fixes https://github.com/namecoin/pkcs11mod/issues/61
> Fix file extension for Windows

- README.md
- pkcs11mod.go
Refs https://github.com/namecoin/pkcs11mod/issues/58
> pkcs11mod: Trace FindObjects

- .cirrus.yml
- p11mod/p11mod.go
- pkcs11mod.go
- testdata/ci-tstclnt-tests.bash
- testdata/try-tstclnt-connect.bash
- types.go
Refs https://github.com/namecoin/pkcs11mod/issues/23
> Add Debian tstclnt test

- .cirrus.yml
- testdata/ci-firefox-tests.bash
Refs https://github.com/namecoin/pkcs11mod/issues/23
> Add Debian Firefox test

- .cirrus.yml
- testdata/ci-chromium-tests.bash
Refs https://github.com/namecoin/pkcs11mod/issues/23
> Add Debian Chromium test

- p11mod/p11mod.go
- testdata/try-firefox-connect.ps1
Refs https://github.com/namecoin/pkcs11mod/issues/36
> p11mod: Implement CloseAllSessions

- .cirrus.yml
Fixes https://github.com/namecoin/pkcs11mod/issues/25
> Cirrus: Add macOS build

- p11mod/p11mod.go
- pkcs11mod.go
- types.go
Refs https://github.com/namecoin/pkcs11mod/issues/58
> Improve GetAttributeValue+FindObjectsInit tracing

- .cirrus.yml
- pkcs11_exported.c
Fixes https://github.com/namecoin/pkcs11mod/issues/65
> Cirrus: Add csbuild

- pkcs11mod.go
> GetAttributeValue: rewrite if-else chain to switch

- .cirrus.yml
- .golangci.yml
Fixes https://github.com/namecoin/pkcs11mod/issues/64
> Cirrus: Add golangci-lint

- p11mod/p11mod.go
> p11mod: Clean up FindObjectsInit

- p11mod/p11mod.go
> p11mod: Conform to errXxx format

- pkcs11mod.go
> Fix some cuddling

- types.go
> toMechanism: Remove unreachable code

- pkcs11mod.go
> Pad+truncate info strings via Sprintf

- .cirrus.yml
- p11mod/p11mod.go
> p11mod / FindObjects: Simplify code

- p11mod/p11mod.go
- pkcs11mod.go
- types.go
> Fix some cuddles

- .cirrus.yml
- p11mod/p11mod.go
- types.go
> Drop redundant "else" after "return" statements

- .cirrus.yml
- .golangci.yml
- p11mod/p11mod.go
- pkcs11mod.go
> Use "var" blocks

- p11mod/p11mod.go
- pkcs11mod.go
- types.go
> Fix cuddles

- .cirrus.yml
- p11mod/p11mod.go
- pkcs11mod.go
- types.go
> Fix cuddled return statements

- .cirrus.yml
- p11mod/p11mod.go
- types.go
> Check for wrapped errors

- pkcs11mod.go
- types.go
> Add blank lines before return/continue

- types.go
> types: Remove redundant Sprintf

- p11mod/p11mod.go
> p11mod: Use short if-statement syntax

- .gitignore
Adding go.mod and go.sum to .gitignore
> Adding go.mod and go.sum to .gitignore

- p11mod/p11mod.go
> Add objects slice description

- p11mod/p11mod.go
> Add CopyObject Function #128

- p11mod/p11mod.go
I had alot of bug unidentified bug in the last branch i had to delete it
> implement initpin function in p11mod #128

- types.go
- types.h
> Add header for C-code

- p11trustmod/backend.go
- p11trustmod/p11trustmod.go
Not sure why Compile Go Latest Tests are failing on my end, maybe through a PR will fix this.
The errors were an easy fix except the funlen errors.
I am trying to formulate helper funcs.
> Go Linter Erros: Api fork 1.1.1.4 draft
